name: Build site
description: Builds the final HTML using Nanoc build

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        cache-version: 1

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install Yarn dependencies
      shell: bash
      run: yarn install

    - name: Build
      shell: bash
      run: bundle exec nanoc
