name: "Ruby Setup and Checks"
description: "Set up Ruby environment and run checks"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install Yarn dependencies
      shell: bash
      run: yarn install

    - run: gem install bundler
      shell: bash

    - run: bundle install
      shell: bash

    - run: bundle exec rubocop
      shell: bash

    - run: bundle exec nanoc check
      shell: bash
