name: Preview Site

on:
  pull_request:
    types: [labeled]

jobs:
  preview:
    if: github.event.label.name == 'preview'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Build site
      uses: ./.github/actions/build-site

    - name: Run Nanoc checks
      uses: ./.github/actions/run-checks

      # preview on GitHub pages
    - name: Deploy to Preview
      uses: ./.github/actions/deploy-preview
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
